services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - shell
      - portfolio
    restart: always
  portfolio:
    build:
      context: .
      dockerfile: infra/docker/base.Dockerfile
      args:
        APP_NAME: "@devfolio/portfolio"
        APP_DIR: "portfolio"
        NEXT_PUBLIC_PORTFOLIO_URL: http://localhost/portfolio
    environment:
      NODE_ENV: production

  shell:
    build:
      context: .
      dockerfile: infra/docker/base.Dockerfile
      args:
        APP_NAME: "@devfolio/shell"
        APP_DIR: "shell"
        NEXT_PUBLIC_PORTFOLIO_URL: http://localhost/portfolio
    depends_on:
      - portfolio

  backend:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/devfolio
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: devfolio-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
