server {
    listen 80;
    server_name vitality-apps.dev www.vitality-apps.dev;

    location / {
        proxy_pass http://shell:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /portfolio/ {
        # rewrite delete "/portfolio" from the URL path,
        # eg. /portfolio/_next/static/... rewrite to /_next/static/...
        rewrite ^/portfolio/(.*)$ /$1 break;
        
        proxy_pass http://portfolio:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://backend:3002;
        proxy_set_header Host $host;
    }
}