events {}

http {
  server {
    listen 80;

    server_name vitality-apps.dev www.vitality-apps.dev;

    location / {
      proxy_pass http://shell:3000/;
    }

    location /portfolio/ {
      proxy_pass http://portfolio:3001/;
    }

    location /api/ {
      proxy_pass http://backend:3002/;
    }
  }
}